<frozen runpy>:128: RuntimeWarning: 'i3_resurrect.main' found in sys.modules after import of package 'i3_resurrect', but prior to execution of 'i3_resurrect.main'; this may result in unpredictable behaviour
<frozen runpy>:128: RuntimeWarning: 'i3_resurrect.main' found in sys.modules after import of package 'i3_resurrect', but prior to execution of 'i3_resurrect.main'; this may result in unpredictable behaviour
<frozen runpy>:128: RuntimeWarning: 'i3_resurrect.main' found in sys.modules after import of package 'i3_resurrect', but prior to execution of 'i3_resurrect.main'; this may result in unpredictable behaviour
<frozen runpy>:128: RuntimeWarning: 'i3_resurrect.main' found in sys.modules after import of package 'i3_resurrect', but prior to execution of 'i3_resurrect.main'; this may result in unpredictable behaviour
